server:
  port: 8890

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nativedemo
    username: postgres
    password: example
  data:
    redis:
      url: redis://localhost:6379
      lettuce:
        pool:
          enabled: true


logging:
  file:
    name: ./logs/sb3d.log
    path: ./logs/

